### ISSUE TITLE
Configuration consistency

### ISSUE THREAD

**Issue by jubianchi** [youknowriad/anchour#17]
As @ratibus pointed out, we should add more consistency in the anchour configuration.

Some steps uses different names for things that matches the same concept. E.g:

``` yml
commands:
  deploy:
    steps:
      -                
        type: "rsync"
        options:
          key_file: "/home/username/.ssh/id_rsa_rsync"
          source_dir: "tmp/minitwitter"
          destination_dir: "tmp/minitwitter2"
        connections:
          destination: "MySSH"

      - 
        type: "ftp"
        options:
          local_dir: "src"
          remote_dir: "test"
        connections:
          connection: "MyFTP"
```

Here, the two connection options should have the same name.

Other options, like `remote_dir`/`destination_dir`, `source_dir`/`local_dir` should also have the same names.

We should run a global check to add consistency to the configuration (at least) :smile:
